function spanelement() {
    window.alert("                                                  Taj Mahal                                                                                                          The Taj Mahal was built in 1648 by Shah Jehan as a memorial to his wife. Today, it is listed as one of the new Seven Wonders of the World. Mughal Emperor Shah Jahan, lost his wife Mumtaz Mahal on June 17, 1631. ... Today, the Taj Mahal is listed as one of the New Seven Wonders of the World.                                                                                             Taj Mahal is a white marble mausoleum built by Mughal Emperor, Shah Jahan in the year 1653. 2) Taj Mahal is built in the loving memory of Mumtaz Mahal, wife of Emperor Shah Jahan. 2) Taj Mahal is built by 20000 artisans in a span of 22 years. 3) Taj Mahal is one of the famous historical monuments in India");
}


function eeee() {
    window.alert("                                    Christ the Redeemer                                                                                                                A symbol of Christianity across the world, the statue has also become a cultural icon of both Rio de Janeiro and Brazil, and is listed as one of the New Seven Wonders of the World. It is made of reinforced concrete and soapstone, and was constructed between 1922 and 1931.                                                                                                                                                                                                                                                                                  Christ the Redeemer is the largest art deco statue in the world. It is 98 feet tall (not including the 26 foot pedestal), and the arms stretch to 92 feet wide. The statue weighs approximately 635 tonnes. Christ the Redeemer is located in the Tijuca Forest National Forest, at the top of the Corcovado Mountain.");
}
document.getElementById("audio").play();



function ddd() {
    window.alert("                                                  Petra                                                                                                           The ancient city of Petra in Jordan became one of the 7 New Wonders of the World when it was chosen in 2007 by a vote of 100 million people. The city's carved rose-red sandstone rock facades, tombs, and temples became known around the world with its appearance in Indiana Jones and The Last Crusade in 1989.                                                                                                                                                                                                                                                     Petra is believed have been established in 312 BC, making it one of the oldest cities in the world. It was the capital city of Nabateans, who were ancient southern Arab people that arrived in Jordan around the 6th century BC. They were essentially the makers of one of the most extraordinary prehistoric civilisations");
}



function qqq() {
    window.alert("                                                  roman colosseum                                                                                                           The Colosseum is built right in the center of Rome, Italy. It is made up of stone and concrete, has about 80 entrances and could hold 50,000 spectators. It was built in only 9 years by almost 60,000 slaves. ... But still Colosseum is considered as one of the seven wonders of the world.                                                                                                                                                                                                                                                               The Roman Colosseum is a wonder of the world. It was located in the middle of Rome in the country of Italy and its remains still stand in that location. The building of the Roman Colosseum began around the year of 72 A.D. and was completed in the year of 81 A.D                                                                                                                                                                                                                 Why the Colosseum is a wonder of the world – what is it famous for? The Colosseum is famous because it is an origin of gladiator battles that took place in the time of Roman Empire. ... When the Colosseum was in its full glory, it must have been a stupendous site of Roman greatness.");
}



function qwqw() {
    window.alert("                                                  chichen itza                                                                                                           Chichén Itzá is a large Mayan city famous for a large, pyramid temple built by the Maya civilization. It is on the Yucatán Peninsula, about 120 km to the east of Mérida. The temple, called Castillo, is about 1 km in diameter. There are many temples and pyramids at Chichen Itza.                                                                                                                                                                                                    Chichen Itza is one of the “New 7 Wonders of the World” due to its large concentration of culturally-significant, ancient manmade wonders and its placing in the top 7 of all nominees during international voting. In 2000, the New7Wonders campaign set out to choose the New 7 Wonders of the World.");
}



function qwerty() {
    window.alert("                                                  Great Wall Of China                                                                                                  The Great Wall of China is a series of fortifications made of stone, brick, tamped earth, wood, and other materials, generally built along an east-to-west line across the historical northern borders of China to protect the Chinese states and empires against the raids and invasions of the various nomadic groups of the ...                                                                                                                                                                                                                           It starts from the eastern coast and stretches into the far western deserts, winding through 404 towns in 15 provincial regions across northern and central China. The Great Wall was declared as one of the New Seven Wonders of the World in 2007. UNESCO acknowledged it as the largest man-made structure on Earth.");
}



function qwrqw() {
    window.alert("                                                  Machu Picchu                                                                                                      Machu Picchu was declared a Peruvian Historical Sanctuary in 1981 and a UNESCO World Heritage Site in 1983. In 2007, Machu Picchu was voted one of the New Seven Wonders of the World in a worldwide Internet poll.                                                                                                                                                                                          At an altitude of about 8000 feet, Machu Picchu, now one of the 7 wonders of the world, is a small city in the Andes, about 44 miles northwest of Cuzco, Peru, which was once the political heart of the Inca Empire.. and about 3000 feet above the Urubamba Valley.                                                                                                                                                                                                        More than 7,000 feet above sea level in the Andes Mountains, Machu Picchu is the most visited tourist destination in Peru. A symbol of the Incan Empire and built around 1450AD, Machu Picchu was designated a UNESCO World Heritage Site in 1983 and was named one of the New Seven Wonders of the World in 2007.");
}
